name: take5
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  flutter_bloc: ^8.1.1
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.2
  flutter_background_service: ^2.4.3
  flutter_local_notifications: ^12.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_screenutil: ^5.5.4
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  dartz: ^0.10.1
  get_it: ^7.2.0
  easy_localization: ^3.0.1
  #notifications
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  multi_select_flutter: ^4.1.2
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.3.0
  signalr_core: ^1.1.1
  quickalert: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.2


flutter:
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-ExtraBold.ttf
          weight: 800
    - family: Marhey
      fonts:
        - asset: assets/fonts/Marhey-Light.ttf
          weight: 300
        - asset: assets/fonts/Marhey-Regular.ttf
          weight: 400
        - asset: assets/fonts/Marhey-Medium.ttf
          weight: 500
        - asset: assets/fonts/Marhey-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Marhey-Bold.ttf
          weight: 700
  uses-material-design: true

  assets:
    - assets/endpoints/
    - assets/translations/
    - assets/images/
    - assets/icons/



